---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "runtime.alquimia.ai/v1alpha1",
          "kind": "AlquimiaAssistant",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "alquimia-operator",
              "app.kubernetes.io/instance": "alquimiaassistant-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "alquimiaassistant",
              "app.kubernetes.io/part-of": "alquimia-operator"
            },
            "name": "alquimiaassistant-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "runtime.alquimia.ai/v1alpha1",
          "kind": "AlquimiaConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "alquimia-operator",
              "app.kubernetes.io/instance": "alquimiaconfig-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "alquimiaconfig",
              "app.kubernetes.io/part-of": "alquimia-operator"
            },
            "name": "alquimiaconfig-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-07-29T21:24:03Z"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0-ocp
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "true"
    features.operators.openshift.io/tls-profiles: "true"
  name: alquimia-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AlquimiaAssistant is the Schema for the alquimiaassistants API
      displayName: Alquimia Assistant
      kind: AlquimiaAssistant
      name: alquimiaassistants.runtime.alquimia.ai
      version: v1alpha1
    - description: AlquimiaConfig is the Schema for the alquimiaconfigs API
      displayName: Alquimia Config
      kind: AlquimiaConfig
      name: alquimiaconfigs.runtime.alquimia.ai
      version: v1alpha1
  description: Aluimia Operator
  displayName: Alquimia Operator
  icon:
  - base64data: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wgARCADIAMgDASIAAhEBAxEB/8QAHAAAAgIDAQEAAAAAAAAAAAAAAAECBgMFBwQI/8QAGwEAAgIDAQAAAAAAAAAAAAAAAAMBAgQFBgf/2gAMAwEAAhADEAAAAfnSMzp048+BxGcimuJjmZYouRxQVZFkSnjZZuEgEC6xjOEUIyjSgBFczTa9QzBI8kHOjjmTWMXtLJ1Kv20to+WnVPDFOeIidHJxKw2hcOMkusYsotAVrmabchsje7ghlZ7yydayuMqli8/N2cf0fW8V1q+o7rCjXROl4sQTPV7FrumVad3TGhGhcotUQGkrQFKZhxa9h6Xt8nQ6x9EZPClKlwpui9XjgJ9OyLGrXvtzo9yx/PeNiWR6HIRQl7rNep3XE3sdajUOM4IUgEqyiHOUTbNV2bfe/key8b514RYvsgkryIUxebhTLficNx/Nubm7pa5puj1FOvr3W+NXHJ9C3HOetcyo3yRbxtFARjIzJxe9dG5z1/K53ovzb9B/MT+bUZxX6AlJMIjVy6XCmWfX8X69TVdAzP2esB3Ry9+vKu67SbVXjrKvLHlx+WwjMVGSLg252bi3XMnmLf8AOX0n81O1rhJR20VNMI5bx19m84hVOr8lNc2iuJkeKdJk0LOjanb6E62tTxvD5L1mEreMZRikb9Qdk7XfQXz93vmmVw3OIy6iep0/sdn1eR2u1OGdpnK5jyjqnKq8YDdNSmyge3xWWmTZapZqRG98zTxOYYCSUWrTFSTY7BueN9jyPO+H7Pa0ue96lzHGm7NfT/zB9Ns33NOW9Q5jXVIZTVDJVM198fsnqdXVfR5UaRjWPhMBcMAEmmC9PmGVipXR2PSF9EfPd8DH9K/NX0i30HnHNOk83rrA2Firi1S77nFbocVQlo064YY+kbBQAQMABMkipRuLY69MpeaJJXx19FfO3TndVbvJoPE3eWjyUrQUwblTvCY+hGCsAY1gBUAAYIGgAABKRYipK4hkiGSIZADKgwoAEAAAAAAAAAAAAAAAgkAAYEAAAAAAAAAAH//EAC0QAAEDAwMDAwQCAwEAAAAAAAQBAgMABQYQESATFDESITAiIyRBJUAyMzRg/9oACAEBAAEFAlTXbat6XRG0vtXn+iqapoiUq7c0+X06+KVdvnXntutLXpWttBbUUbUOIzLTcUHbS4yJUuNQbc10Xkq0i6W2zE3RwGOig0tKtSlwxVGVERUi/ToLaHENNCkBl4ry86WHGVLRrWxMLMhDjOy1Voi5ElaYx5kX6d9LUsZEeTmRTk8F133rxwxiwd2q1fMgjtiFFzGS716tMZ8yL9PBK7OboaLX61RU9UzkVtltbrqc1jYY8iviWuF8jpHa71jK+8q/Rwx8YWepER7bgIoZFfr9cN6xe3dhbDS2BDGlvOJ44z5lX6N6Y1ZHC2Wjg1DmGIcLNCQ0mG7jdwNScF0tAff3JazQ/d3LG6k/xEs0s1DiRCt8VdToZo6sBWyuouLok0vHCR/UY5au5Pd3LljmpdziEou4yl6hzdEpy1eWbTV+q39tMKZsEXL0Rt63rfjjtEFRCtMvEs9b8Y3+uG8f6kpKXyui1hq/xV1X+NrbjDDIRIQGZj0T3ukdojuAy/iXb/nptSR7arWFyfhlM6o+m+m29WrEiDaAtg1tjzvxwRdY09EN1d9rRZFcmuHkegxVq7D9rcdLXYSrotqx0W165z424p7UNH1p3LVzfvJytpXZHK7dMrD0xWzBmQImyH3Qa2R3TLSTKhcrh84XTfXbS0Q+7loiTqzc8eP7sEqFpMBYzxJ7LdX2ku6ZmrklmfPJUK/j5tyijdNIyNIIj5unF8FsOW3lJK2SPICxieMS/YzTiiK5QAu1Y92yEz9eWt/g7qXocYl+xmXCGF87wrc0RHLR5nVX5MVBiMOPFhLhe30PqNfs5hpCARPQ+PrUcMY7JHI1Dbh1fmAPltxBeVSzxaRr9kiCKekgiipy05aKukMNEmSFL/SiyuD0Lk4q1JksNTZDK+pzJiP/ACv/xAA1EQAABQIDBAgFBAMAAAAAAAAAAQIDBAUREBIhEyIxsQYgMkFRYXGBFCMkNJFAQuHwocHR/9oACAEDAQE/AQR2F9ARd5i98SxMHjluMosZh1xDSczh2LzC65ARpnv6EE12Go+J/gHiYPqXFV6RJjGbEXVXj3F/0Mxp9XXnO6vM+H99Az0YO3zXPwQlxSiSTZSd7WFxJisNx9onjzxPEiIyM7jpFVjjJ+FZPePj5F/IodF+K+okdjuLx/gJIkFlSViGbxFT1nK9uRYxqftm85qC0mhRpUDxddJlBuK4FqIza6xULr/cdz9P7oEpS2kkp4EL4VEvrFe3IhIqbbOiN4xDmyXpGupchTX8jmzPgYqbWpOkDxr7mzp7lu+xf5HRVoruun5F1J6DVLUSS105CNSjPef/AAENpbLKgrBKzQZGQm78czHHC46RFmgn6kOjB/LcT5ljEpLz+8vdITYrUaUtLZeHLC+EjdjHfwBGFmkz3cJ7HxMVxrxIUB7Yych/u5iNHVKc2aBHp8eEW0XqfiYjzW5SlJb7hVfvF+3IsYze1dJAqLlmsvj1anDOJJ2iOB6l6iBJdNCHjLKoSJbso7uGKFxc9hVPu1+3IsYUfYIzr4mJT+2cuXDqmklcSEmQmKyp5XAhTakmoErdsZCh8XPb/Yqf3a/bkQaivPdlIjQUR99epibNz/Lb4ddaEuJNCyuRiPFZillZTYUqQ0wa9odr2CpkTtZiDtUZT2NQ/Mdf0PQv1/8A/8QAIxEAAgICAgEEAwAAAAAAAAAAAAECEQMQITESICJBUTJAUv/aAAgBAgEBPwETL4Evs7KKK2x7o8SimeLKKKGtPa1HH8sdI7JaaVDRQ9xXBihfLJz+Nz7KKPGxoktIjyP2R9GT8iWVIjOTkImh6RiXuMjEIoyq50Rwf0VWpdaYjE/cT7ELVK9WMl0WTab4EQdMkR5EqLG9PU+h6QhStCZ5WQJPkvcpEtoTI8uh8GMk+TllUSl9DY/RYmeVmOSXZ5xHkRKbY2N+qyyyyyy/0f/EAD0QAAECAgUJBgELBQAAAAAAAAECAwARBBASIFETISIxMkFxgsEjMEJSYXKhFEBTYGJzkbHR4fEkM2OBkv/aAAgBAQAGPwL6qdkyop8xzCO1fSj2icaTriuEhGtz/qDZccHH5n2abLe9xWqASMu55l/pXpuoTxVBybiXJa7JnBrmVWIsOcQce+TSKUClnwo3qgJQkJSNQEW3nAhPrBTRW5Dzr/SO1fWr0nmqpHL1g1haCD0hptoheTGkoY96KXSE9iNhJ8RqyaO0pB8O5PGC484VquUjl6wb2WyZyXm7gYRmzwlrU2M6z6QlCBZQkSAEWG89IXq+z6wVKJUo6ybtI5esK4XVFYtvp8KtUoKSJpOaUFHh1pPcpWodq9pnhuhx9zZQJwt9w6SjepHL1hXCqykWjgItPnlES8B2TCXEbSYS4nUqCRtozis3WGPCpWlw31NURJ+2vpfpHL1gxNzsk/GJNpl676sknTVPawqWwfcKnEYG++95ES/H+KqQ7uKs3C/SOXrXKdtflEaRkjyitteBqQvESv0heLkvh+8Or8qCe4pHL1ibipem+Clvs0fGM91CsUgwg/avufen8hFK+6V+V8NtILizuSIQV2EmkbtZTL+YKlEqOJvs+0RzVzuUhGC5/D9odR5kkXc0BdI/p2vXaMWWGwnFW8xQufp3CE4ACEj1vvNedE/wqfb3WpjhXNCbDX0itUBQTlXvpF9K6Hz9L6E+uepKcBfZe3JVn4VN0lPsV0q+UO9s4lUsmdSYkMwi0+5ZwTvMFFHnRmvTaP8AuGydZSIofP0vqdPAVKV3AQT2jWieG6FtL2VCULaXrTAcGds5lpxEFFCTZ/yr6CCtxRWs6yqpv2iKHz9LwQBMmEoTqEEDaVmjP3CXPDqUMRAWkzSROcJDem6nxjVK637RFE5ul2QzmJq/uHX6RM6oJ3bu6yOUVkvLeb9oiic/S5ZQm0YtK0nccKsmjZ3nHvVqeAWltMwk4wWnEAp/KFJwMqke0RRObpVoNKPruib6+VMWW0hIgkmQgob2cce+DrWvUQd4gpbaySj4rU60cBAyjaXJarQnGg2hPBNcgcorBMaRknyj5mkLZcBA3Z42XfwEaLSzxjQbSjjnjtHCRh9Vf//EACkQAAIBAgUCBgMBAAAAAAAAAAABERAhMUFRcZFhgSChscHR8DDh8UD/2gAIAQEAAT8hhusBUgt2tiG4+FJLvAZJ7DuHZQvAkRSCBEWapk6pwWJX88Bmrwd16GLJiyrJNE0bsTR4owFWC6Y5XXFIwRG5ncGLG8kOskiwGSOkmKMW4sVVUkSKy1I0LMLvUkyGyUJMaI5vX9FiFPpbH9hNfvowYj8b4FXPY0NehgiaN3qrCW2pidMqK+AoS1IUSMnQwhDiwX5Ynh3LstsA8UnDTfRSNg8MDi2N9EW0SEq4YKJI3YqDgngx72pipEuEKFjcx6IbnYdw3aFgPDG+D1XovUSMeE4SQ9czHssxuh3l9g7cA+hwVqNxhxbGU7yIUkXU33Coo9MypZdo8/AsDEPKjbZQnaaNwoWAqcH+qn0XmPAwJS1vMfAc2OuXRLIiup0WJH4w4t1To3A0sydRWohbVKw7iEmATk0uhedYfL5vAVFQYMkiQiTt0avYcfGWJbdZLTiQ5B4bxQlcglmLtISbBouub7hUxGal9hKLkoYtgRy4rI4v3HsRMddF3JfU6Mkskqt1bhDkAgvNtwRI9xA6/qzOG50Bl8MnfoYL9O3QixP7JUYiIUbLFFJKUyNm/kQyShWSH2EWFwnq+KNwT4Hh7Qdtau4YxU+i1f2IhdWZ3G0jbcJZsbbNKGHyoxhs/wBo5HFlItsqYl1EKJzsOHmNdUSYpiXdv2oOZOWVtWXkhsfhcDc0mm+nvoMo4b/dEy/UQztg6UBfof0xR6DBklq3HGkETmW4urigjO3laklqNtTs4J6IlaFupbUsxBGLpzNkQ5essXcu9w1Hg+/QhJ0kPIaGYujsWMNLGNFInCfq5Z9CWV9qOjMFRMxsg6p2P2DzDWZxZLETAzB3Q3GjRPQUaH2LIaV2e4tyUxqRr9xsbolzK+Yf2nUOwyW+5Z5cCki56F22PCcSy7l9dxL77PPUVWDbQjNYCPpSI3tPyEIizdqMZNjhRN2+G6VkoR9xdetU7V9vs1EUE5V1syrfujy8LCNs0h0zpb3HP8oqun7UFZ+TYiROU8GTNLD9r18qYssbt0rP0EKQkWSWREMzwb7aHbGpfmydhwksG9bEy3UZErTgha8kqW2sv30tBm7bUVH4Lq3dMz27CMJlPkS1ex1WTJWrX/SUMDyxRf6al7frUt0+jZDz4SrEzoGFEwS4yHuJzax6jUPwuiay3swTFhmWBu9Jh8JOdXT7dkPPh6yhsskhFua+xoLcyEu2OynZOgmy5RAvHZWBzfarpB9oyHllgiic83TIsYd2bKUwy3A/Ky4IqcsxhmKFa/UtC+kySp9MyHl0cDHalHJikKL64myq8xJJGLY+Zaz5/wAxzSsyLSYkqhDwm1q/RsjYXHDk8kWVKIneEnJsSMD/AAxRRUQsPwPtV5nsqL5JTfGl7HZyLLj/ABR+CP8ABH4o/wAUEEEEfj//2gAMAwEAAgADAAAAEEi/YGmqxrC6f/aVRRTG1XFJIePfdkQKfCI5JYdPUas6cFDBRpwUPcfxLoNkLaF2/j7jQtQfSqV9R4v16px92nRm/fUzGCq1attegOeDTyNQhoEE00X5fgbTS0Xn1FICxQwfSd9FUg5BpeQQfQQ01f8A31UMEEEEEEEN38MEEEEH/8QAJxEBAAIBAgUFAAMBAAAAAAAAAQARITFBUWFxgaEQkbHB0SBA8OH/2gAIAQMBAT8QTcnCRWqAFEexFGYlAgmYzGUmIEpomGY6glO5boD3YzS7mPmq8yrUdfxcwKg4jBZNHoQozFLe0OgPDqTgcR7DreSd3QUORt2HaEDl4WeVPiL4Go65B+4lYRTZTe7XxnHqKE9OuscmjbjB9Y8jXgHB9wZ1RggN/wAK/wCX01PiDAGh0NPQN09Rp+vQM55/nmDlSQ+gmsS2hV0C2ceJyBsdCh2hhUAAbBoR4J1ljwXfadDq/niXIq4QMDj255TnUW6+l/7p7QDeMP14+ILPTFRt88gX4uCKyAd7X4Jhlc5Us+LAM7JSLRwfbt29yFyA2JrFDftCEck9z6hCZqMI82TzX3DN8J7j+TDKvSUPddXofb5nWSHVw1ZdMG4WNkdLYD4JSy8ij0QAtSupk8hBZ6DXZk+zqw6wLnPD76Eu4BrgDoaHl5y6lK50G70323iICiUxKLF29DWEW9eDP566+mlN7DbUnvk5dIlQc8Mm9cHg9JkrNjQOh96xV0vt64FriKn4Rw/Yb6DB+941t/CqqabL2ePWEmo3Rq7B3YrDq4u8N1mjhwnhQzkFM1cXB7syhT7HT9+IAX5njyOXz0/nWwFI7kfiLrq33VZwkxfK/wBgm13HV+LglBfsec+JnTkH3x+OX9//xAAgEQEBAQEAAwADAAMAAAAAAAABABEhEDFBIDBRcZGx/9oACAECAQE/EE+lh88H0meDETJ5D8HbyMGw3qQ3y/tOJjx4E5engh9gXrMnpJcSWLHJur4GDNPBCpX1ehcLBxG3+ZVjDDWyfNn3BQEjA+R11ggniuWdbsuksctOx0mxbC9RCERFB/P+Te/9ZJwMly7j2HZeI+LEIGwSHWWf6uL2zhtKeSsdu4Kwh7YD6ukvgOuS9PFl2XgGHSV7S3bBTFgw1tGR88rwaIR3my3bJweiD02/PAW+RyIo6Sum3NT7Nvj7+gQHIh5LGuv0ba2tv5f/xAAoEAEAAgEDAwQDAQEBAQAAAAABABEhMUFhEFFxgZGhscHR8CDhMPH/2gAIAQEAAT8QqanzPMwb7Zl8QNL+qG881Bg188HtLqYKKolEPafaUoKduzzA0XbqrKWGN3vKO7K5ZXMsTPQ6yxFMDeTG8WOMmZTK9j89Udnqd4OLjc3/AOOgXDQOwXMoRTr2/abzPbtBfN3YgbG73i3LlpeZKxoay3vcogi4sy4cMbSOpE2+GXLZbbM2GExKidO/5EDMvQZXNQLP+JMsG972/wCwGo93aAGobveLHRa6m9ErCHpBrocvGYcHsufO6m29jMLNIIRHJECx3qweYNXFvVEhcK7gfqWKtMIDdrWLuJ6QbRIL6ofS5bAsplwrT7gSma2B9H7IXR5YR9lJe9XA+4u5p0Xcswg30VhmSd3T5XQa8mEC6FwZDd5wEegaO0wVZ77RKUsbveXvU5+5DfgPWo3POQLe09beYIowGAJrQYK1X+yzYkd0bq6cXT7T+G2grV3vGuvmL+4W9Gza4vJUops8qnc9RIPeXiDNnD3bfiDc+g6WoLozxN2v2ND1itRcmAlprA0Jas0N+0A9Qe8rpJnh23F9+BSjUAQG0ANIbJYFZewZXATS4AOzkGj1XxFDUY/SvhMu3viV5R7XmP4baJWvoSsIwOneUkSalm4NkguxYKo1TDQZN0bMSuR0YPRKjfUmDrRzNK46YDTsNIgM5e0SycuCUpRhd3Y7wPUj3miycYJyG7bbitBERQUGgS9tBHA6Ke5qeCmbqI3g+gHBOR5wtshbrK/5MxX/AHYg3l0i3ENGulOHV8QGsQwFeiGqc6QdtoqeSYCbNempHI4elNOXvFaarUL/ADBLW3vol+cn+klg9yh5vZhg9IoagPSE2dvyaKXwHVvYYnErRJtV36LUYvob8y99/wAkfwG0W4PQbjQ+DxOFbxd3d1iO2WJkFJN9hjd2eTR/7OZrHH1n9z4EeiAzXlCula9MxDQPuM+DvAqoJGQfGsO7l0kwHL0DlIHLLJVMPZcIKDx0WpTyxVlkriP5Dad3EWRdIJ9CGplyZ38bHvGmV1u/Y8n6d5hiyNhuuEsiX2EDqtFcjZ6QsmFQyn5jPkIMqa14jZwf9hpE2x4mB2ZfPS0gEOF+YPWEgAUBoEpFFQtVtHjQ5UWBC2LFvrIAhYQd2oUFnPsnZ5fZljSlPny/hpDLAtSgIeNUNfHNPcWYxnWDTMA3rXRwE8lPowUbyOIIC0Hu8/B+INIwWxoK/viaoHZAZO8yG1u6QK/dBHgr7ar2D1mpH6J5/vonYi6LfRalD4wudAq40W0eWn24ifMsYPXuvPx0XfMougD5/gWak0pLpO6v6+EEuPU7TW+7H0iWnZqIAtnLqxE9V4MToHhxLPpaO4w+0ZdYF7W/hHIit5i3KfOYq9PYia/d+5buPDF4vmV3vUiFQNmi4taks2/5PEsA+LbPkaeD3YLC97PX1iKmGkGoRU21B5Q/mG7r8xfqLYSqK/AhbWussHTjoEUaw8eueTJ6pCVUq5yRZ0fxtERzrNHUpGqc9MfcbkCL3rr3cUR872knrNUFoU8MAWvJlIgNRohrKdnzF3PRn5j8IBVrQ9oFOD8xI4NqqyWefSlQhiPiKBbZIeIhCctH5T8wKRKTZmqbS07ZRSzTylIljRTKxxL6FweXTz7GYHgHrA+XxobBHZdvo6B1Q1qtVEJZfyPM0RUMLhyAhZOfhL9zVHSJrrCBqdirjrHU0Qq2IO+Ie79JrRMch/zYB6R0I6zK8KO0711fjHdJTsloFPY9OeXotFxhlp7HEX2Tw/UbuqroF9HVn/2ESs4yM/AZqSs3WflQYvoNY4L3mfRrtBYbyQCMKwbE7x7tBYGmVT3Fxv5i9KBlIZXcmc9xSkP2IHQDQDaVg4vtd5fLQbpLyCxhncPh7mKHdbVJVlBgrvACrs7OZZrTlQbT6IhtjvtCO4MZt1yvaj1ZqSu26viwfUSugxH26pmBTSCXNH0H/wBJeqzunYcjSckoZUQmNo4TME2uS39T3B8miwsyKDT7gebeN4yErK7lelRn8mVOD0KuBXRqsUeIa6mtNDda2DMOCsxuu68rbNxAE1Dd7fZPki38/uNQlMO3TWJTBEueT1IdfUwnJCE8M5Iu52S2gyvzKSsGc5YnvNfM5dP6nbKvnKjpVwKiLzArVdiKzyIZ4P5/5C8lUaBMjTNtv2dYLA47OSOaGNHtB1SazSJFKMgBl3LjcvNaXmJEvoq+igXX8SMDqFTXZQDA7roHLBLAU18h+/1NWBaa5mEbHB89AgXNv8JUS+iVGA5GTbgCHUM471FxdpIuy7jiY44w0aauUz+k2dYT9k6fVg+YoG632vCzHoPmABDUOV3XVeWCke10B3uIKPGlwHY+5pA6BX+dYlRI6dKl6hLZV8GB4QiO/MTvqmlPLdRtc55lHefwWyHgtqMh1qjV0e0aFU0av2JqwQq0G7KGQxdYedB6W8S90DeAfPd5egdA/wBsTolxKldCRXwFZWFbsDWW9mVY2+1z+GAgc7ovp8S3FW98aiBXQOgf7WuqXErqp/1TDoC4Ff7X/TFdalErrTD/AMC3/wCh6v8A1P/Z"
    mediatype: "image/jpeg"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - runtime.alquimia.ai
          resources:
          - alquimiaassistants
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - runtime.alquimia.ai
          resources:
          - alquimiaassistants/finalizers
          verbs:
          - update
        - apiGroups:
          - runtime.alquimia.ai
          resources:
          - alquimiaassistants/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - runtime.alquimia.ai
          resources:
          - alquimiaconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - runtime.alquimia.ai
          resources:
          - alquimiaconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - runtime.alquimia.ai
          resources:
          - alquimiaconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: alquimia-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: alquimia-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: alquimia-operator
          control-plane: controller-manager
        name: alquimia-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:9b7aabfbead92df3a4afeb1854e45a92f23da52321d1705fce444510fa856145
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: jlcruzalquimiaai/alquimia-runtime-operator@sha256:63e38c3c0819fb804f03f1022cc2cf94bee30b0646068ade61beffdca657e13e
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: alquimia-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: alquimia-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ia
  - agents
  links:
  - name: Alquimia Operator
    url: https://alquimia-operator.domain
  maturity: alpha
  provider:
    name: alquimiaai
  version: 0.0.1
  minKubeVersion: "1.26.0"
  relatedImages:
    - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:9b7aabfbead92df3a4afeb1854e45a92f23da52321d1705fce444510fa856145
      name: kube-rbac-proxy
    - image: jlcruzalquimiaai/alquimia-runtime-operator@sha256:63e38c3c0819fb804f03f1022cc2cf94bee30b0646068ade61beffdca657e13e
      name: manager
